In [1]:
import pandas as pd
import cenpy as cenpy
import requests

/home/lyzka/anaconda3/lib/python3.7/site-packages/libpysal/weights/util.py:20: UserWarning: geopandas not available. Some functionality will be disabled.
  warn('geopandas not available. Some functionality will be disabled.')

## Resources
- [cenpy PyPI](https://pypi.org/project/cenpy/)  
- [cenpy Website](https://cenpy-devs.github.io/cenpy/)
- [cenpy API Reference](https://cenpy-devs.github.io/cenpy/api.html)
- [cenpy GitHub Repo](https://github.com/cenpy-devs/cenpy)
- [US Census Data via CenPy (towards data science)](https://towardsdatascience.com/scraping-us-census-data-via-cenpy-9aeab12c877e)  
- [Getting Census Data in 5 Easy Steps (towards data science)](https://towardsdatascience.com/getting-census-data-in-5-easy-steps-a08eeb63995d)
- [Cenpy - Filter data during querying (stack overflow)](https://stackoverflow.com/questions/62944948/cenpy-filter-data-during-querying)
- [Using the Census Bureau's API (medium)](https://medium.com/@shep.nathan.d/using-the-u-s-census-bureaus-api-af113337f478)
- [FIPS codes](https://www2.census.gov/geo/docs/reference/codes/files/)
- [Census Burearu YouTube tutorial](https://www.youtube.com/watch?v=K0-ifZS0mQI&feature=emb_title&ab_channel=U.S.CensusBureau)
- [American Community Survey 5-Year Data (2009-2018)](https://www.census.gov/data/developers/data-sets/acs-5year.html)
- [Census Datasets](https://api.census.gov/data.html)
- [Notes on ACS Estimate and Annotation Values (weird values)](https://www.census.gov/data/developers/data-sets/acs-1year/notes-on-acs-estimate-and-annotation-values.html)

## Contents
- [Cenpy Attempt Did Not Work](#Cenpy-Attempt-Did-Not-Work)  
- [Pulling from Census API Directly](#Pulling-from-Census-API-Directly)
- [Another possible method, individual variable route](#Another-possible-method,-going-the-individual-variable-route)

# Cenpy Attempt Did Not Work

In [2]:
# Caroline's Census key, DON'T USE
cc_census_key = 'abaab7067d6de5d6a0216fca0b8fca4e9015a87f'

In [3]:
# This was the only case study example I could find but seemed
# code was outdated, didn't work as-is
# https://towardsdatascience.com/scraping-us-census-data-via-cenpy-9aeab12c877e

# Call list of available identifiers for Census Dat APIs
datasets_df = cenpy.explorer.available(verbose=True)

datasets_df.head(2)

,c_isTimeseries,publisher,temporal,spatial,programCode,modified,keyword,contactPoint,distribution,description,...,c_isCube,c_isAggregate,c_valuesLink,c_groupsLink,c_examplesLink,c_tagsLink,c_variablesLink,c_geographyLink,c_dataset,vintage
NONEMP1999,NaN,U.S. Census Bureau,1999/1999,United States,006:007,2017-02-09,(),"{'fn': 'Nonemployer Statistics staff', 'hasEma...","{'@type': 'dcat:Distribution', 'accessURL': 'h...",Nonemployer Statistics is an annual series tha...,...,True,True,https://api.census.gov/data/1999/nonemp/values...,https://api.census.gov/data/1999/nonemp/groups...,https://api.census.gov/data/1999/nonemp/exampl...,https://api.census.gov/data/1999/nonemp/tags.json,https://api.census.gov/data/1999/nonemp/variab...,https://api.census.gov/data/1999/nonemp/geogra...,"(nonemp,)",1999.0
NONEMP1997,NaN,U.S. Census Bureau,1997/1997,United States,006:007,2017-02-09,(),"{'fn': 'Nonemployer Statistics staff', 'hasEma...","{'@type': 'dcat:Distribution', 'accessURL': 'h...",Nonemployer Statistics is an annual series tha...,...,True,True,https://api.census.gov/data/1997/nonemp/values...,https://api.census.gov/data/1997/nonemp/groups...,https://api.census.gov/data/1997/nonemp/exampl...,https://api.census.gov/data/1997/nonemp/tags.json,https://api.census.gov/data/1997/nonemp/variab...,https://api.census.gov/data/1997/nonemp/geogra...,"(nonemp,)",1997.0

In [4]:
# Set the index name
datasets_df = datasets_df.rename_axis('api')

In [5]:
# Export the datasets dataframe to a .csv
datasets_df.to_csv('datasets.csv')

In [6]:
# Import the datasets dataframe to a .csv
datasets_df = pd.read_csv('datasets.csv')
datasets_df.head(2)

,api,c_isTimeseries,publisher,temporal,spatial,programCode,modified,keyword,contactPoint,distribution,...,c_isCube,c_isAggregate,c_valuesLink,c_groupsLink,c_examplesLink,c_tagsLink,c_variablesLink,c_geographyLink,c_dataset,vintage
0,NONEMP1999,NaN,U.S. Census Bureau,1999/1999,United States,006:007,2017-02-09,(),"{'fn': 'Nonemployer Statistics staff', 'hasEma...","{'@type': 'dcat:Distribution', 'accessURL': 'h...",...,True,True,https://api.census.gov/data/1999/nonemp/values...,https://api.census.gov/data/1999/nonemp/groups...,https://api.census.gov/data/1999/nonemp/exampl...,https://api.census.gov/data/1999/nonemp/tags.json,https://api.census.gov/data/1999/nonemp/variab...,https://api.census.gov/data/1999/nonemp/geogra...,"('nonemp',)",1999.0
1,NONEMP1997,NaN,U.S. Census Bureau,1997/1997,United States,006:007,2017-02-09,(),"{'fn': 'Nonemployer Statistics staff', 'hasEma...","{'@type': 'dcat:Distribution', 'accessURL': 'h...",...,True,True,https://api.census.gov/data/1997/nonemp/values...,https://api.census.gov/data/1997/nonemp/groups...,https://api.census.gov/data/1997/nonemp/exampl...,https://api.census.gov/data/1997/nonemp/tags.json,https://api.census.gov/data/1997/nonemp/variab...,https://api.census.gov/data/1997/nonemp/geogra...,"('nonemp',)",1997.0

In [7]:
datasets_df = datasets_df.sort_values(by='api')
datasets_df.head(3)

,api,c_isTimeseries,publisher,temporal,spatial,programCode,modified,keyword,contactPoint,distribution,...,c_isCube,c_isAggregate,c_valuesLink,c_groupsLink,c_examplesLink,c_tagsLink,c_variablesLink,c_geographyLink,c_dataset,vintage
447,ABSCB2017,NaN,U.S. Census Bureau,unidentified,NaN,006:007,2020-04-30 00:00:00.0,(),"{'fn': 'ASE Staff', 'hasEmail': 'mailto:erd.an...","{'@type': 'dcat:Distribution', 'accessURL': 'h...",...,NaN,True,https://api.census.gov/data/2017/abscb/values....,https://api.census.gov/data/2017/abscb/groups....,https://api.census.gov/data/2017/abscb/example...,https://api.census.gov/data/2017/abscb/tags.json,https://api.census.gov/data/2017/abscb/variabl...,https://api.census.gov/data/2017/abscb/geograp...,"('abscb',)",2017.0
451,ABSCBO2017,NaN,U.S. Census Bureau,unidentified,NaN,006:007,2020-04-30 00:00:00.0,(),"{'fn': 'ASE Staff', 'hasEmail': 'mailto:erd.an...","{'@type': 'dcat:Distribution', 'accessURL': 'h...",...,NaN,True,https://api.census.gov/data/2017/abscbo/values...,https://api.census.gov/data/2017/abscbo/groups...,https://api.census.gov/data/2017/abscbo/exampl...,https://api.census.gov/data/2017/abscbo/tags.json,https://api.census.gov/data/2017/abscbo/variab...,https://api.census.gov/data/2017/abscbo/geogra...,"('abscbo',)",2017.0
453,ABSCS2017,NaN,U.S. Census Bureau,unidentified,NaN,006:007,2020-04-30 00:00:00.0,(),"{'fn': 'ASE Staff', 'hasEmail': 'mailto:erd.an...","{'@type': 'dcat:Distribution', 'accessURL': 'h...",...,NaN,True,https://api.census.gov/data/2017/abscs/values....,https://api.census.gov/data/2017/abscs/groups....,https://api.census.gov/data/2017/abscs/example...,https://api.census.gov/data/2017/abscs/tags.json,https://api.census.gov/data/2017/abscs/variabl...,https://api.census.gov/data/2017/abscs/geograp...,"('abscs',)",2017.0

In [8]:
# View what APIs you can pull using cenpy
apis = datasets_df['api'].unique()
apis[:20]

array(['ABSCB2017', 'ABSCBO2017', 'ABSCS2017', 'ACSCD1132011',
       'ACSCD1152015', 'ACSCP1Y2010', 'ACSCP1Y2011', 'ACSCP1Y2012',
       'ACSCP1Y2013', 'ACSCP1Y2014', 'ACSCP1Y2015', 'ACSCP1Y2016',
       'ACSCP1Y2017', 'ACSCP1Y2018', 'ACSCP1Y2019', 'ACSCP3Y2012',
       'ACSCP3Y2013', 'ACSCP5Y2015', 'ACSCP5Y2016', 'ACSCP5Y2017'],
      dtype=object)

In [9]:
# from cenpy import products <-- wouldn't work

# Pulling from Census API Directly

Table: https://data.census.gov/cedsci/table?q=ACSDP1Y2019.DP05&tid=ACSDP5Y2018.DP05&hidePreview=false  
ACS DEMOGRAPHIC AND HOUSING ESTIMATES   
Survey/Program: American Community Survey   
2018: ACS 5-Year Estimates Data Profiles  
TableID: DP05

In [10]:
# Reference: Census YT tutorial: https://www.youtube.com/watch?v=K0-ifZS0mQI&feature=emb_title&ab_channel=U.S.CensusBureau
# Added in 'NAME' parameter
# Edit 'DP05' table
# add in state:48 for TX

### Format URL should be in

In [11]:
example_url = 'https://api.census.gov/data/2018/acs/acs5/profile?get=group(DP05),NAME&for=county:*&in=state:48&key=abaab7067d6de5d6a0216fca0b8fca4e9015a87f'

### Pulling data for 2018 DP05 table (ACS 5-Year Demographic and Housing Estimates)

In [12]:
# Set base url
url = 'https://api.census.gov/data/2018/acs/acs5/profile?'

# Set params
params = {
    'get': 'group(DP05),NAME',
    'for': 'county:*',
    'in': 'state:48',
    'key': 'abaab7067d6de5d6a0216fca0b8fca4e9015a87f'
}

# Make a request and display the response code.
res = requests.get(url,params)
res

In [13]:
df = pd.DataFrame(res.json())
df.head(3)

,0,1,2,3,4,5,6,7,8,9,...,707,708,709,710,711,712,713,714,715,716
0,NAME,DP05_0031PM,DP05_0032E,DP05_0032M,DP05_0032PE,DP05_0032PM,DP05_0033E,DP05_0033M,DP05_0033PE,DP05_0033PM,...,DP05_0029PEA,DP05_0030MA,DP05_0030EA,DP05_0030PMA,DP05_0030PEA,DP05_0031MA,DP05_0031EA,DP05_0031PEA,state,county
1,"Austin County, Texas",0.6,87.0,1.9,-888888888,-888888888,29565,-555555555,29565,-888888888,...,None,None,None,None,None,None,None,None,48,015
2,"Kenedy County, Texas",20.5,34.7,38.9,-888888888,-888888888,595,181,595,-888888888,...,None,None,None,None,None,None,None,None,48,261

In [14]:
# Set the values in the first row to the columns
df.columns = df.iloc[0]

In [15]:
# Drop the first row
df = df.iloc[1:, :]

df.head(3)

,NAME,DP05_0031PM,DP05_0032E,DP05_0032M,DP05_0032PE,DP05_0032PM,DP05_0033E,DP05_0033M,DP05_0033PE,DP05_0033PM,...,DP05_0029PEA,DP05_0030MA,DP05_0030EA,DP05_0030PMA,DP05_0030PEA,DP05_0031MA,DP05_0031EA,DP05_0031PEA,state,county
1,"Austin County, Texas",0.6,87.0,1.9,-888888888,-888888888,29565,-555555555,29565,-888888888,...,None,None,None,None,None,None,None,None,48,015
2,"Kenedy County, Texas",20.5,34.7,38.9,-888888888,-888888888,595,181,595,-888888888,...,None,None,None,None,None,None,None,None,48,261
3,"Nueces County, Texas",0.1,79.3,0.3,-888888888,-888888888,360486,-555555555,360486,-888888888,...,None,None,None,None,None,None,None,None,48,355

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 1 to 254
Columns: 717 entries, NAME to county
dtypes: object(717)
memory usage: 1.4+ MB

In [17]:
df.to_csv('./data/api_pull.csv')

### Now Pulling Headers

In [18]:
# Per directions in tutorial at https://www.youtube.com/watch?v=K0-ifZS0mQI&feature=emb_title&ab_channel=U.S.CensusBureau,
# downloaded table and saved csv data with overlays
# These headers correspond to the codes in the previous table

header_df = pd.read_csv('./data/ACSDP5Y2018.DP05_data_with_overlays_2020-10-14T224250.csv')
header_df.head(3)

,GEO_ID,NAME,DP05_0031PM,DP05_0032E,DP05_0032M,DP05_0032PE,DP05_0032PM,DP05_0033E,DP05_0033M,DP05_0033PE,...,DP05_0029M,DP05_0029PE,DP05_0029PM,DP05_0030E,DP05_0030M,DP05_0030PE,DP05_0030PM,DP05_0031E,DP05_0031M,DP05_0031PE
0,id,Geographic Area Name,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!RACE!!Total population,Margin of Error!!RACE!!Total population,Percent Estimate!!RACE!!Total population,...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...
1,0500000US48001,"Anderson County, Texas",0.5,87.5,1.9,(X),(X),57863,*****,57863,...,97,8199,(X),3827,25,46.7,0.5,4372,93,53.3
2,0500000US48003,"Andrews County, Texas",1.4,78.9,4.5,(X),(X),17818,*****,17818,...,118,1843,(X),813,50,44.1,1.4,1030,79,55.9

In [19]:
# Get rid of geo ID column
header_df = header_df.iloc[:, 1:]

header_df

,NAME,DP05_0031PM,DP05_0032E,DP05_0032M,DP05_0032PE,DP05_0032PM,DP05_0033E,DP05_0033M,DP05_0033PE,DP05_0033PM,...,DP05_0029M,DP05_0029PE,DP05_0029PM,DP05_0030E,DP05_0030M,DP05_0030PE,DP05_0030PM,DP05_0031E,DP05_0031M,DP05_0031PE
0,Geographic Area Name,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!RACE!!Total population,Margin of Error!!RACE!!Total population,Percent Estimate!!RACE!!Total population,Percent Margin of Error!!RACE!!Total population,...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...
1,"Anderson County, Texas",0.5,87.5,1.9,(X),(X),57863,*****,57863,(X),...,97,8199,(X),3827,25,46.7,0.5,4372,93,53.3
2,"Andrews County, Texas",1.4,78.9,4.5,(X),(X),17818,*****,17818,(X),...,118,1843,(X),813,50,44.1,1.4,1030,79,55.9
3,"Angelina County, Texas",0.3,77.6,0.9,(X),(X),87607,*****,87607,(X),...,39,13627,(X),5956,40,43.7,0.3,7671,47,56.3
4,"Aransas County, Texas",0.6,94.0,2.2,(X),(X),24763,*****,24763,(X),...,83,6581,(X),3189,70,48.5,0.6,3392,37,51.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,"Wood County, Texas",0.7,86.8,2.4,(X),(X),43815,*****,43815,(X),...,139,11770,(X),5469,112,46.5,0.7,6301,100,53.5
251,"Yoakum County, Texas",4.1,90.8,15.1,(X),(X),8571,*****,8571,(X),...,82,971,(X),462,*****,47.6,4.1,509,82,52.4
252,"Young County, Texas",1.6,79.4,5.1,(X),(X),18114,*****,18114,(X),...,91,3585,(X),1587,78,44.3,1.6,1998,65,55.7
253,"Zapata County, Texas",4.4,80.6,14.1,(X),(X),14369,*****,14369,(X),...,200,1999,(X),892,21,44.6,4.4,1107,200,55.4
254,"Zavala County, Texas",1.3,76.9,4.1,(X),(X),12131,*****,12131,(X),...,26,1665,(X),724,24,43.5,1.3,941,27,56.5

In [20]:
header_df.to_csv('./data/header_pull.csv')

### Examine the columns

In [21]:
api_cols = list(df.columns)

In [22]:
header_cols = list(header_df.columns)

In [23]:
len(api_cols), len(header_cols)

(717, 357)

In [24]:
# Examine the difference in columns
difference = set(api_cols) - set(header_cols)

print(len(difference))

list(difference)[:10]

359

['DP05_0002MA',
 'DP05_0043PEA',
 'DP05_0021MA',
 'DP05_0060PEA',
 'DP05_0026PEA',
 'DP05_0067PEA',
 'DP05_0063PEA',
 'DP05_0076EA',
 'DP05_0086MA',
 'DP05_0060PMA']

In [25]:
# By looking some of these up in the .csv, it appears at least some are blank

In [26]:
df.isna().sum()

0
NAME              0
DP05_0031PM       0
DP05_0032E        0
DP05_0032M        0
DP05_0032PE       0
               ...
DP05_0031MA     243
DP05_0031EA     254
DP05_0031PEA    254
state             0
county            0
Length: 717, dtype: int64

In [27]:
# Save the null values to a new dataframe.
nan_df = pd.DataFrame(df.isna().sum(), columns=['NaN Counts'])

# Display the entries with NaN counts for every one of 254 counties.
nan_df[nan_df['NaN Counts'] == 254]

              NaN Counts
0
DP05_0032EA          254
DP05_0033EA          254
DP05_0033PEA         254
DP05_0034MA          254
DP05_0034EA          254
...                  ...
DP05_0029PEA         254
DP05_0030EA          254
DP05_0030PEA         254
DP05_0031EA          254
DP05_0031PEA         254

[294 rows x 1 columns]

In [28]:
# 294 of the values are blank
# But even if we dropped all the blank columns we'd still have 423, versus 356 in the other...

## Create a dictionary of the columns and their identifiers

In [29]:
row_one_df = header_df.iloc[:1, :]

row_one_df

,NAME,DP05_0031PM,DP05_0032E,DP05_0032M,DP05_0032PE,DP05_0032PM,DP05_0033E,DP05_0033M,DP05_0033PE,DP05_0033PM,...,DP05_0029M,DP05_0029PE,DP05_0029PM,DP05_0030E,DP05_0030M,DP05_0030PE,DP05_0030PM,DP05_0031E,DP05_0031M,DP05_0031PE
0,Geographic Area Name,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!RACE!!Total population,Margin of Error!!RACE!!Total population,Percent Estimate!!RACE!!Total population,Percent Margin of Error!!RACE!!Total population,...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!65 ye...,Margin of Error!!SEX AND AGE!!Total population...,Percent Estimate!!SEX AND AGE!!Total populatio...

In [30]:
# Convert the row of the dataframe into a list
descriptions = row_one_df.values.tolist()

# The output is a nested list so convert it to a regular list
descriptions = descriptions[0]

# View the first five entries
descriptions[:5]

['Geographic Area Name',
 'Percent Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Female',
 'Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females)',
 'Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females)',
 'Percent Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females)']

In [31]:
# Check the length of the headers and their descriptions
len(header_cols), len(descriptions)

(357, 357)

In [32]:
# Create a dictionary from a zipped list of the header columns and descriptions
header_dict = dict(zip(header_cols, descriptions))

# View the first five entries in the dictionary
list(header_dict.items())[:5]

[('NAME', 'Geographic Area Name'),
 ('DP05_0031PM',
  'Percent Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Female'),
 ('DP05_0032E',
  'Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females)'),
 ('DP05_0032M',
  'Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females)'),
 ('DP05_0032PE',
  'Percent Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females)')]

In [33]:
# Rename the colums in the original dataframe according to the dictionary
df.rename(columns = header_dict, inplace=True)

In [34]:
# Drop columsn with NaN values
df.dropna(axis=1, inplace=True)

In [35]:
# Display the dataframe
df

,Geographic Area Name,Percent Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Percent Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Percent Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Estimate!!RACE!!Total population,Margin of Error!!RACE!!Total population,Percent Estimate!!RACE!!Total population,Percent Margin of Error!!RACE!!Total population,...,DP05_0004PMA,DP05_0004PEA,DP05_0018PMA,DP05_0018PEA,DP05_0025PMA,DP05_0028PMA,DP05_0028PEA,DP05_0029PMA,state,county
1,"Austin County, Texas",0.6,87.0,1.9,-888888888,-888888888,29565,-555555555,29565,-888888888,...,(X),(X),(X),(X),(X),(X),(X),(X),48,015
2,"Kenedy County, Texas",20.5,34.7,38.9,-888888888,-888888888,595,181,595,-888888888,...,(X),(X),(X),(X),(X),(X),(X),(X),48,261
3,"Nueces County, Texas",0.1,79.3,0.3,-888888888,-888888888,360486,-555555555,360486,-888888888,...,(X),(X),(X),(X),(X),(X),(X),(X),48,355
4,"Colorado County, Texas",0.1,85.6,0.3,-888888888,-888888888,21022,-555555555,21022,-888888888,...,(X),(X),(X),(X),(X),(X),(X),(X),48,089
5,"San Patricio County, Texas",0.5,86.1,1.6,-888888888,-888888888,67046,-555555555,67046,-888888888,...,(X),(X),(X),(X),(X),(X),(X),(X),48,409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,"McCulloch County, Texas",2.2,86.7,7.6,-888888888,-888888888,8098,-555555555,8098,-888888888,...,(X),(X),(X),(X),(X),(X),(X),(X),48,307
251,"Lee County, Texas",1.3,87.2,4.5,-888888888,-888888888,16952,-555555555,16952,-888888888,...,(X),(X),(X),(X),(X),(X),(X),(X),48,287
252,"Ellis County, Texas",0.2,80.7,0.6,-888888888,-888888888,168838,-555555555,168838,-888888888,...,(X),(X),(X),(X),(X),(X),(X),(X),48,139
253,"Kerr County, Texas",0.5,86.6,1.9,-888888888,-888888888,51365,-555555555,51365,-888888888,...,(X),(X),(X),(X),(X),(X),(X),(X),48,265
254,"Falls County, Texas",0.8,88.8,3.0,-888888888,-888888888,17299,-555555555,17299,-888888888,...,(X),(X),(X),(X),(X),(X),(X),(X),48,145

In [36]:
df.to_csv('./data/dp05_with_headers.csv')

# Another possible method, going the individual variable route
- [DATA GEMS: How to Extract Data from the Census API](https://www.youtube.com/watch?v=0DVdHquaRiU)
- [Census API: Datasets in /data/2018/acs/acs5/profile and its descendants](https://api.census.gov/data/2018/acs/acs5/profile.html)