In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
data = pd.read_csv('../data/texas_combined_cleaned_WITH_Census_Percentage_FA.csv')

In [8]:
data.head()

,county_name,total_cases,total_fatalities,death_rate,sex_age_median_age_in_years,health_ins_noninst_pop_private,health_ins_noninst_pop_public,inc_med_hhld_inc_dol,inc_mean_hhld_inc_dol,inc_per_capita_inc_dol,...,percent_inc_hhlds_less_than_10_000,percent_inc_hhlds_10_000_to_14_999,percent_inc_hhlds_15_000_to_24_999,percent_inc_hhlds_25_000_to_34_999,percent_inc_hhlds_35_000_to_49_999,percent_inc_hhlds_50_000_to_74_999,percent_inc_hhlds_75_000_to_99_999,percent_inc_hhlds_100_000_to_149_999,percent_inc_hhlds_150_000_to_199_999,percent_inc_hhlds_200_000_or_more
0,anderson,2922.0,39,0.013347,39.1,27169,16504,43355,55852,16868,...,0.058874,0.074184,0.137493,0.130628,0.162282,0.197217,0.112097,0.087004,0.025639,0.014582
1,andrews,567.0,10,0.017637,31.2,11313,4332,74233,94962,31190,...,0.054829,0.031046,0.052832,0.095316,0.124546,0.152687,0.132171,0.220407,0.072259,0.063907
2,angelina,2277.0,90,0.039526,37.2,46576,31836,47714,61152,22322,...,0.083553,0.054381,0.132963,0.119611,0.132248,0.188318,0.130364,0.105805,0.031998,0.020758
3,aransas,340.0,18,0.052941,49.6,13508,10606,44865,75471,30939,...,0.088634,0.055768,0.123198,0.120971,0.149385,0.152990,0.094996,0.111005,0.050466,0.052587
4,archer,133.0,1,0.007519,44.5,6429,2718,64476,80073,31806,...,0.037515,0.059724,0.086735,0.117947,0.103541,0.165066,0.138655,0.187875,0.059424,0.043517

In [70]:
counties_live = pd.read_csv('/Users/ferasaltwal/Downloads/covid-19-data-master/live/us-counties.csv')

In [71]:
counties_live

,date,county,state,fips,cases,deaths,confirmed_cases,confirmed_deaths,probable_cases,probable_deaths
0,2020-10-25,Autauga,Alabama,1001.0,2059,31.0,1831.0,29.0,228.0,2.0
1,2020-10-25,Baldwin,Alabama,1003.0,6658,69.0,5644.0,65.0,1014.0,4.0
2,2020-10-25,Barbour,Alabama,1005.0,1033,9.0,731.0,9.0,302.0,0.0
3,2020-10-25,Bibb,Alabama,1007.0,840,14.0,771.0,10.0,69.0,4.0
4,2020-10-25,Blount,Alabama,1009.0,1932,25.0,1497.0,25.0,435.0,0.0
...,...,...,...,...,...,...,...,...,...,...
3240,2020-10-25,Sweetwater,Wyoming,56037.0,462,2.0,438.0,NaN,24.0,NaN
3241,2020-10-25,Teton,Wyoming,56039.0,747,1.0,713.0,NaN,34.0,NaN
3242,2020-10-25,Uinta,Wyoming,56041.0,431,3.0,346.0,NaN,85.0,NaN
3243,2020-10-25,Washakie,Wyoming,56043.0,144,7.0,132.0,NaN,12.0,NaN
3244,2020-10-25,Weston,Wyoming,56045.0,127,0.0,97.0,NaN,30.0,NaN

In [73]:
counties_live.sample(5)

,date,county,state,fips,cases,deaths,confirmed_cases,confirmed_deaths,probable_cases,probable_deaths
1576,2020-10-25,Perry,Missouri,29157.0,795,8.0,795.0,8.0,NaN,NaN
1790,2020-10-25,Atlantic,New Jersey,34001.0,5008,264.0,4997.0,253.0,11.0,11.0
1042,2020-10-25,Grayson,Kentucky,21085.0,498,15.0,NaN,NaN,NaN,NaN
2885,2020-10-25,Juab,Utah,49023.0,246,3.0,246.0,3.0,NaN,NaN
814,2020-10-25,Clay,Iowa,19041.0,526,4.0,526.0,4.0,NaN,NaN

In [75]:
florida_data = counties_live[counties_live['state'] == 'Florida']

In [76]:
florida_data.head(2)

,date,county,state,fips,cases,deaths,confirmed_cases,confirmed_deaths,probable_cases,probable_deaths
322,2020-10-25,Alachua,Florida,12001.0,10044,74.0,NaN,74.0,NaN,NaN
323,2020-10-25,Baker,Florida,12003.0,1750,19.0,NaN,19.0,NaN,NaN

In [77]:
counter = 0
for i in florida_data.cases:
    counter += i
print(counter)

778628

In [79]:
counties_live['date'].max()

'2020-10-25'

In [80]:
us_live = pd.read_csv('/Users/ferasaltwal/Downloads/covid-19-data-master/live/us-states.csv')

In [81]:
us_live

,date,state,fips,cases,deaths,confirmed_cases,confirmed_deaths,probable_cases,probable_deaths
0,2020-10-25,Alabama,1,184355,2866,157881.0,2680.0,26474.0,186.0
1,2020-10-25,Alaska,2,13439,64,0.0,64.0,13439.0,0.0
2,2020-10-25,Arizona,4,238200,5874,NaN,NaN,NaN,NaN
3,2020-10-25,Arkansas,5,105318,1797,98213.0,1640.0,7105.0,157.0
4,2020-10-25,California,6,907597,17345,905017.0,17345.0,2580.0,0.0
5,2020-10-25,Colorado,8,94204,2243,NaN,NaN,NaN,NaN
6,2020-10-25,Connecticut,9,66052,4577,NaN,NaN,NaN,NaN
7,2020-10-25,Delaware,10,23961,681,NaN,NaN,NaN,NaN
8,2020-10-25,District of Columbia,11,16767,642,16767.0,642.0,0.0,0.0
9,2020-10-25,Florida,12,778628,16428,0.0,16428.0,778628.0,0.0
10,2020-10-25,Georgia,13,360344,7626,336504.0,7626.0,23840.0,0.0
11,2020-10-25,Guam,66,5110,70,5090.0,70.0,20.0,0.0
12,2020-10-25,Hawaii,15,14706,211,NaN,NaN,NaN,NaN
13,2020-10-25,Idaho,16,58964,573,51819.0,527.0,7145.0,46.0
14,2020-10-25,Illinois,17,379958,9787,375245.0,9517.0,4713.0,270.0
15,2020-10-25,Indiana,18,165038,4130,162607.0,3894.0,2431.0,236.0
16,2020-10-25,Iowa,19,115841,1634,115841.0,1634.0,0.0,0.0
17,2020-10-25,Kansas,20,78202,975,NaN,NaN,NaN,NaN
18,2020-10-25,Kentucky,21,97774,1470,NaN,NaN,NaN,NaN
19,2020-10-25,Louisiana,22,183575,5837,179842.0,5631.0,3733.0,206.0
20,2020-10-25,Maine,23,6201,146,5521.0,146.0,680.0,0.0
21,2020-10-25,Maryland,24,140547,4096,140425.0,3956.0,122.0,140.0
22,2020-10-25,Massachusetts,25,149488,9839,146023.0,9616.0,3465.0,223.0
23,2020-10-25,Michigan,26,175460,7522,157829.0,7182.0,17631.0,340.0
24,2020-10-25,Minnesota,27,133855,2402,133431.0,2335.0,424.0,67.0
25,2020-10-25,Mississippi,28,115088,3255,101683.0,2944.0,13405.0,311.0
26,2020-10-25,Missouri,29,175148,2857,173904.0,2856.0,1244.0,1.0
27,2020-10-25,Montana,30,27880,298,27880.0,298.0,0.0,0.0
28,2020-10-25,Nebraska,31,63215,603,21417.0,197.0,41798.0,406.0
29,2020-10-25,Nevada,32,95703,1748,95703.0,1748.0,0.0,0.0
30,2020-10-25,New Hampshire,33,10238,473,9628.0,467.0,610.0,6.0
31,2020-10-25,New Jersey,34,230257,16285,228468.0,14496.0,1789.0,1789.0
32,2020-10-25,New Mexico,35,41040,965,41040.0,965.0,0.0,0.0
33,2020-10-25,New York,36,500201,33059,495548.0,28406.0,4653.0,4653.0
34,2020-10-25,North Carolina,37,260128,4182,250776.0,4122.0,9352.0,60.0
35,2020-10-25,North Dakota,38,37724,461,37719.0,456.0,5.0,5.0
36,2020-10-25,Northern Mariana Islands,69,88,2,88.0,2.0,0.0,0.0
37,2020-10-25,Ohio,39,198115,5206,NaN,NaN,NaN,NaN
38,2020-10-25,Oklahoma,40,116736,1249,0.0,1249.0,116736.0,0.0
39,2020-10-25,Oregon,41,41739,654,39991.0,359.0,1748.0,295.0
40,2020-10-25,Pennsylvania,42,198756,8730,NaN,NaN,NaN,NaN
41,2020-10-25,Puerto Rico,72,62503,801,31737.0,610.0,30766.0,191.0
42,2020-10-25,Rhode Island,44,30118,1177,0.0,924.0,30118.0,253.0
43,2020-10-25,South Carolina,45,170678,3802,163143.0,3567.0,7535.0,235.0
44,2020-10-25,South Dakota,46,39203,375,37979.0,NaN,1224.0,NaN
45,2020-10-25,Tennessee,47,243508,3105,230438.0,739.0,13070.0,2366.0
46,2020-10-25,Texas,48,906838,17998,862861.0,13402.0,43977.0,4596.0
47,2020-10-25,Utah,49,104882,572,38568.0,318.0,66314.0,254.0
48,2020-10-25,Vermont,50,2073,58,2073.0,58.0,0.0,0.0
49,2020-10-25,Virginia,51,173371,3579,NaN,NaN,NaN,NaN
50,2020-10-25,Virgin Islands,78,1346,21,1346.0,21.0,0.0,0.0
51,2020-10-25,Washington,53,106932,2396,103598.0,2324.0,3334.0,72.0
52,2020-10-25,West Virginia,54,21906,423,20567.0,419.0,1339.0,4.0
53,2020-10-25,Wisconsin,55,208917,1814,198210.0,1781.0,10707.0,33.0
54,2020-10-25,Wyoming,56,11041,68,9396.0,NaN,1645.0,NaN